name: "Deploy to aws"

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: "Setup node.js"
        uses: actions/setup-node@v4
        with:
          node-version: '21'

      - name: "Checkout code"
        uses: actions/checkout@v2

      - name: "Install dependencies"
        run: npm install

      - name: "Install Jest"
        run: npm install jest --save-dev

      - name: "Fix Jest Permissions"
        run: chmod +x ./node_modules/.bin/jest

      - name: "Install pm2 globally"
        run: npm install pm2 -g

      # - name: "Run the test"
      #   run: npm test

        - name: "Run the test"
          run: npm test -- --passWithNoTests

      - name: "Deploy to aws"
        run: pm2 restart index.js || pm2 start index.js

      - name: Check if pm2 is installed
        run: |
          if ! command -v pm2 &> /dev/null
          then
            npm install pm2 -g
          else
            echo "pm2 already installed"
          fi
